### ISSUE TITLE
Add some figure to quantify a reference mismatch

### ISSUE THREAD

**Issue by Mc-Zen** [tingerrr/typst-test#17]
for example the number of mismatched pixels. 

This would be very helpful in the case when tests fail due to extremely minor changes. Especially PNG rendering is sometimes subject to minute differences even when PDF/SVG output is not (at least visually) affected. 

Thanks for this project - I've been using it for some months now and it is amazing :)

**Comment by tingerrr** [comment]
I've been meaning to improve the diff images, but I haven't gotten around to it since I'm working on the cli/lib separation to provide the Typst compiler instead of calling Typst from the system.

Something I thought of was using a simple contour algorithm to add boxes which highlight minor changes like those. This should be easy enough today, so I'll take a look when I have time.

**Comment by Mc-Zen** [comment]
Ah yes, this would be great as well! It would be best if you can turn the boxes on/off with a flag when running the tests. 

If it is not too much work, the number of differing pixels would still be a helpful tool and - I think - could easily be computed and shown in the CLI output. 

Out of curiosity: why do you want to provide the compiler instead of calling the Typst executable?

**Comment by Mc-Zen** [comment]
Sounds very exciting, thanks for elaborating.
